AllCops:
  # Target Ruby 2.7 only
  TargetRubyVersion: 2.7
  # Display all verbose info on failures to help people triage how to fix
  DisplayCopNames: true
  DisplayStyleGuide: true
  # Don't lint bin/scripts - Possibly remove for V2
  # Don't lint package files
  Exclude:
    - bin/**/*
    - vendor/**/*
    - node_modules/**/*

# More flexible array alignment
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# More flexible hash alignment
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# 140 character width
# TOFIX: Remove Exclude in V2
Layout/LineLength:
  Max: 140
  Exclude:
    - 'spec/**/*'

# TOFIX: Remove in V2
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Exclude BlockLength from spec tests as this will break all spec tests.
# It should be added to the rubocop-rspec defaults ideally.
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Allow method names starting with get or set, as we use some DSL's
Naming/AccessorMethodName:
  Enabled: false

# TOFIX: Remove in V2
Naming/MemoizedInstanceVariableName:
  Enabled: false

# TOFIX: Document / Discuss in V2
Naming/MethodParameterName:
  AllowedNames:
    - '_'
    - 'e'
    - 'i'
    - 'id'
    - 'to'

# We don't enforce documentation comments on Modules/Classes
Style/Documentation:
  Enabled: false

# Prefer simple looking "template" style tokens like `%{name}`, `%{age}`
Style/FormatStringToken:
  EnforcedStyle: template

# Disable multi-line chaining check
# TOFIX: Document / Discuss in V2
Style/MultilineBlockChain:
  Enabled: false

# Prefer Double quotes in Ruby across the codebase/s
Style/StringLiterals:
  EnforcedStyle: double_quotes
