AllCops:
  # Target Ruby 2.7 only
  TargetRubyVersion: 2.7
  # Display all verbose info on failures to help people triage how to fix
  DisplayCopNames: true
  DisplayStyleGuide: true
  # Don't lint generated bin/scripts
  Exclude:
    - 'bin/**/*'
  # Since Rubocop v0.83 - New cops introduced can be auto-enabled / disabled
  # Lets remove the warnings for these
  NewCops: enable

# More flexible array alignment
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# More flexible hash alignment
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# 140 character width
Layout/LineLength:
  Max: 140
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

# Tests are disabled from all Length checks by design
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Tests are disabled from all Length checks by design
Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

# Tests are disabled from all Length checks by design
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

# Allow method names starting with get or set, as we use some DSL's
Naming/AccessorMethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - '_'
    - 'e'
    - 'i'
    - 'id'
    - 'to'

# We don't enforce documentation comments on Modules/Classes
Style/Documentation:
  Enabled: false

# Prefer simple looking "template" style tokens like `%{name}`, `%{age}`
Style/FormatStringToken:
  EnforcedStyle: template

# Disable multi-line chaining check
Style/MultilineBlockChain:
  Enabled: false

# Prefer Double quotes in Ruby across the codebase/s
Style/StringLiterals:
  EnforcedStyle: double_quotes
