AllCops:
  TargetRubyVersion: 2.7

  # Output settings
  DisplayCopNames: true
  DisplayStyleGuide: true

  Exclude:
    - 'bin/**/*' # don't lint generated bin/scripts

  # Since Rubocop v0.83 - New cops introduced can be auto-enabled / disabled
  # Lets remove the warnings for these
  NewCops: enable

# Don't enforce comments classes
Style/Documentation:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/MixinGrouping:
  Exclude:
    - 'spec/**/*'

Style/FormatStringToken:
  EnforcedStyle: template # Prefer simple looking "template" style tokens like `%{name}`, `%{age}`

# More flexible array alignment
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# More flexible hash alignment
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

# Tests are disabled from all Length checks by design
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Tests are disabled from all Length checks by design
Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

# Tests are disabled from all Length checks by design
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

# 140 character width
Layout/LineLength:
  Max: 140
  Exclude:
    - 'spec/**/*'

# Disable multi-line chaining check
Style/MultilineBlockChain:
  Enabled: false

# Allow method names starting with get or set, as we use some DSL's
Naming/AccessorMethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - '_'
    - 'e'
    - 'i'
    - 'id'
    - 'to'

# Prefer double quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes
