# This allows us to merge arrays for Exclude rules on AllCops or a specific cop
inherit_mode:
  merge:
    - Exclude

AllCops:
  # Display all verbose info on failures to help people triage how to fix
  DisplayCopNames: true
  DisplayStyleGuide: true
  # Enable all NewCops by default (Even new 1.x cops)
  NewCops: enable
  # Target Ruby 2.7 only
  TargetRubyVersion: 2.7
  # Don't lint package files
  Exclude:
    - vendor/**/*
    - node_modules/**/*

# More flexible array alignment
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# More flexible hash alignment
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# We have a linelength of 140 characters across the codebase/s
Layout/LineLength:
  Max: 140
  Exclude:
    - '^Given'
    - '^When'
    - '^Then'

Metrics/BlockLength:
  Exclude:
    # RakeTasks defined here are massive declarative blocks
    - lib/tasks/**/*
    - Rakefile
    # Specs deliberately will almost always break this cop (It should be added to rubocop-rspec defaults ideally)
    - spec/**/*

# Allow method names starting with get or set, as we use some DSL's
Naming/AccessorMethodName:
  Enabled: false

# We don't enforce documentation comments on Modules/Classes
Style/Documentation:
  Enabled: false

# Prefer simple looking "template" style tokens like `%{name}`, `%{age}`
Style/FormatStringToken:
  EnforcedStyle: template

# Prefer Double quotes in Ruby across the codebase/s
Style/StringLiterals:
  EnforcedStyle: double_quotes
