# frozen_string_literal: true

source "https://rubygems.org"

# Rails
gem "rails", "~> 8.0.2"

# Add view_component to allow testing rules for it
gem "view_component"

group :development, :test do
  gem "citizens-advice-style",
      path: "../"
end
